# -*- coding: utf-8 -*-
"""2025-07-25 - ViT - Shared Output Subspace in ViT.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1V6EdFjAPKC5DSQkXr9Fw-8fusMpF43ps

# ▂▂▂▂▂▂▂▂▂▂▂▂

# Latent Attention for Vision Transformers

The goal of this notebook is to create a small proving ground for testing out the impact of Multihead Latent Attention on a Transformer with the addition of a shared output projection.

I'm using the Vision Transformer architecture because it can be trained relatively quickly from scratch (< 15 minutes) on a simple benchmark task, CIFAR-10 and CIFAR-100.

## Preliminary Observations

These should not be taken as claims, just data points that I found interesting and seem worth **investigating**.

Based on my experiences so far, I do think we can say that:

* The addition of an output latent space is by no means catastrophic.
* Acceptable sizes for the space seem to be on the same scale as the other latents. (i.e., the output space doesn't appear to need to be dramatically larger than the others).

And then here are some observations based on limited data which seem interesting to investigate more thoroughly:

1. Similar to the practice in MoE models of using dense FFNs in early layers, it may be helpful to use **dense MHA** in **early layers** as well.
2. In this context, the addition of an output subspace seems to be a **blanket improvement** to MLA, but does this hold in other settings?
3. It may be the case that MLA benefits from being used **in conjunction** with shared spaces on the FFN, and this may be more true when an output subspace is used with attention.

### 1.1 Standard MLP + 3 Attention Types

I did some ad hoc exploring of different parameter combinations, eventually settling on one because most of my attempts to improve on it stopped working. (So it's most likely a local minima).

After some initial exploring of parameter choices to find what seemed to generally work well, I landed on the below configuration and compared across the three attention variants I'm exploring.

All three variants use:

* A standard FFN with 896 neurons: "`mlp.896`"
* A model size of 320 "`d320`"
* 5 attention heads of size 64 "`ah5.64`"

For the MLA variants, the latent dimension sizes are formatted as "`mla.(q latent).(kv latent).(output latent or -1)`"

```
===== Acc. === Acc./M ======== Configuration ===========================
1     84.12    7.4245    11.33M - mlp.896 - mha          - d320 - ah5.64
2     80.89    8.7828     9.21M - mlp.896 - mla.96.64.-1 - d320 - ah5.64
3     81.95    9.3764     8.74M - mlp.896 - mla.96.64.96 - d320 - ah5.64
```

**Row 1 - Baseline**
* This uses vanilla MLP and attention.
* Its test accuracy of `84.12` is significantly higher than the MLA variants.
* It has the lowest accuracy-per-parameter at `7.42`.

**Row 2 - MLA**
* Standard MLA with no output subsace.
* This test case has a query latent of length 96 and a kv latent of length 64.
* It's more parameter efficient than the baseline, but has the lowest accuracy.

**Row 3 - MLA w/ output latent**

* Using the same configuration as row 2, but adding a shared latent space of size 96 to the output heads.
* Fewer parameters, higher accuracy and efficiency than standard MLA.

#### Counterpoints

Thoughts on how the results could be flawed, how the baselines might be improved, etc.

_Is the baseline over-parameterized?_

* I initially tried the baseline with 960 neurons in the MLP, and accuracy improved when I lowered this to 896.
    * Over-parameterization seems to be an important / challenging part of this. A model could unfairly appear worse in both accuracy and efficiency if there are too many parameters in the wrong place.

_MLA Implementation_

* I could explore the placement of bias terms and normalizations to make sure that I haven't artificially hampered the baseline MLA somehow.
    * I could try swapping in a different implementation of MLA.

_Problem Scale_

* Again, I've seen performance increase on multiple occassions after removing parameters. Perhaps the output subspace is helpful on this small task because it helps avoid overfitting, but would become more inhibitive when training a more powerful model.

### 1.2. With Decomposed MLP

I wanted to try using the MLA output latent in tandem with an MLP that uses latents as well. Perhaps latents perform best when all components are using them?

I used a latent dimension of 128 for the MLP. I didn't explore this value much.


```
===== Acc. === Acc./M ======== Configuration ==============================

                                 (Dense MLP)
1     84.12    7.4245   11.33M - mlp.896      - mha          - d320 - ah5.64                                 
2     80.89    8.7828    9.21M - mlp.896      - mla.96.64.-1 - d320 - ah5.64
3     81.95    9.3764    8.74M - mlp.896      - mla.96.64.96 - d320 - ah5.64

                                 (Decomposed)
4     83.38    9.358      8.91M - dcmp.896.128 - mha          - d320 - ah5.64                                 
5     81.12    11.282    7.19M - dcmp.896.128 - mla.96.64.-1 - d320 - ah6.64
6     82.25    12.557    6.55M - dcmp.896.128 - mla.96.64.96 - d320 - ah6.64
```

In terms of accuracy:
* It reduced the accuracy of MHA (row 1 vs. row 4)
* This change improved the accuracy for both versions of MLA.
* MLA with an output subspace improved by +0.3 vs. +0.23 with no output subspace.

_However_:

* I should re-run these with 5 attention heads for both to make sure their improvement is due to the decomposition and not the increased head count!

---

Bonus data point:

The above four tests all used 2 initial dense layers with 960 neurons.
The below two used 2 dense layers with 1280 neurons and performed worse than with 960.

```
===== Acc. === Acc./M ======== Configuration ==============================
1    80.64    10.639    7.58M - dcmp.896.128 - mla.96.64.-1 - d320 - ah6.64
2    81.71    11.757    6.95M - dcmp.896.128 - mla.96.64.96 - d320 - ah6.64
```

#### Counterpoints

* Perhaps it's a fluke related to the change in attention head count.
* Seems like a property that you'd want to test more rigorously before drawing conclusions about?

### 1.3. Max Accuracy

```
===== Acc. === Acc./M ======== Configuration ==============================
1    84.12    7.4245    11.33M - mlp.896      - mha          - d320 - ah5.64
2    83.38    9.358      8.91M - dcmp.896.128 - mha          - d320 - ah5.64
3    82.25    12.557    6.55M  - dcmp.896.128 - mla.96.64.96 - d320 - ah6.64
4    81.34    11.424    7.12M  - dcmp.896.128 - mla.64.48.-1 - d320 - ah6.64
```

For the three attention variants, these are the highest accuracies I've achieved.

Note that, for standard attention, the library forces the head count to divide evenly into the model dimension, so I can't increase it to 6.

I've tried a number of configurations aimed at getting MLA to match the performance of MHA--the thought being that I should be able to reallocate the saved parameters in a way that makes the model more capable--but so far it's falling short.

### 1.4. Max Efficiency

It seems to be fairly easy with the MLA + subspace variant to trade accuracy for increased "accuracy per parameters". Probably true of the other attention types as well.

For example, the query-kv-output latent spaces can be further reduced to 64.32.64

```
1    81.45    14.441    5.64M - dcmp.896.128 - mla.64.32.64 - d320 - ah6.64
2    81.53    14.797    5.51M - dcmp.896.128 - mla.64.32.48 - d320 - ah12.32
```

A higher number of smaller attention heads also looks promising.

# ▂▂▂▂▂▂▂▂▂▂▂▂

# Classes

## LatentAttention
"""

import torch
from torch.nn import functional as F
from torch import nn

class LatentAttention(nn.Module):
    """Multihead Latent Attention using shared query and kev-value subspaces.

    This is a modified version of the original standard mha implementation from
    the timm library.
    """

    fused_attn: True

    def __init__(
            self,
            dim: int,
            num_heads: int = 8,
            head_dim: int = None,

            qk_norm: bool = False,

            # ======================
            #    Shared Subspaces
            # ======================
            q_proj_dim: int = None,
            kv_proj_dim: int = None,
            o_proj_dim: int = None,

            output_subspace: bool = False,

            scale_norm: bool = False,

            o_bias: bool = True,

            qkv_bias: bool = False,

            # Unused by ViT
            attn_drop: float = 0.,
            o_drop: float = 0,
            norm_layer = None, #Optional[Type[nn.Module]] = None,
    ) -> None:
        """Initialize the Attention module.

        Args:
            dim: Input dimension of the token embeddings
            num_heads: Number of attention heads
            qkv_bias: Whether to use bias in the query, key, value projections
            qk_norm: Whether to apply normalization to query and key vectors
            o_bias: Whether to use bias in the output projection
            attn_drop: Dropout rate applied to the attention weights
            o_drop: Dropout rate applied after the output projection
            norm_layer: Normalization layer constructor for QK normalization if enabled
        """
        super().__init__()

        #assert dim % num_heads == 0, 'dim should be divisible by num_heads'

        if qk_norm or scale_norm:
            assert norm_layer is not None, 'norm_layer must be provided if qk_norm or scale_norm is True'

        self.num_heads = num_heads  # Default is 3 for tiny

        # Default behavior is to force this ratio, but that's just a
        # convention (probably with some merit?), not a requirement.
        if head_dim is None:
            self.head_dim = dim // num_heads # For  tiny: 192 / 3 = 64
                                             # For small: 384 / 6 = 64
        else:
            self.head_dim = head_dim

        # Softmax scaling factor
        self.scale = self.head_dim ** -0.5

        self.fused_attn = True #use_fused_attn()

        # ======================
        #    Shared Subspaces
        # ======================
        self.q_proj_dim = q_proj_dim
        self.kv_proj_dim = kv_proj_dim

        self.q_proj = nn.Linear(dim, q_proj_dim, bias=qkv_bias)
        self.kv_proj = nn.Linear(dim, kv_proj_dim, bias=qkv_bias)

        # Define RMSNorm for the projections
        self.q_proj_norm = nn.RMSNorm(self.q_proj_dim)
        self.kv_proj_norm = nn.RMSNorm(self.kv_proj_dim)

        # Original ViT, for reference.
        #self.qkv = nn.Linear(dim, dim * 3, bias=qkv_bias)
        #self.o = nn.Linear(dim, dim, bias=o_bias)

        # ========================
        #     Attention Heads
        # ========================

        self.q = nn.Linear(
            q_proj_dim,
            self.num_heads * self.head_dim,
            bias=qkv_bias  # ViT sets this true, I have it false.
                           # It decreased speed measurably, and didn't improve accuracy.
        )
        self.kv = nn.Linear(
            kv_proj_dim,
            2 * self.num_heads * self.head_dim, # Key and Value projections concatenated.
            bias=qkv_bias
        )

        # Store the flag for whether to create a shared output subspace.
        self.output_subspace = output_subspace

        if output_subspace:
            # Store the dimension.
            self.o_proj_dim = o_proj_dim

            self.o_proj = nn.Linear(
                o_proj_dim,
                dim,
                bias=False
            )

            # An RMSNorm in between the per-head projection and the shared one
            # hurt performance.
            #self.o_proj_norm = nn.RMSNorm(self.o_proj_dim)

            self.o = nn.Linear(
                self.num_heads * self.head_dim,
                o_proj_dim,
                bias=o_bias
            )
        else:
            self.o = nn.Linear(
                self.num_heads * self.head_dim,
                dim,
                bias=o_bias
            )

        # The ViT doesn't actually use these.
        #self.o_drop = nn.Dropout(o_drop)
        self.attn_drop = nn.Dropout(attn_drop)
        #self.norm = norm_layer(dim) if scale_norm else nn.Identity()


    def forward(
            self,
            x: torch.Tensor,
            attn_mask = None  #: Optional[torch.Tensor] = None,
    ) -> torch.Tensor:

        # B (Batch Size) - Number of Images (256).
        # N (Num Patches): Number of patches per image, plus `[CLS]` (65)
        # C (Channels): Embedding dimension of a "token", 192.
        B, N, C = x.shape

        # ======================
        #    Shared Subspaces
        # ======================

        # Project the token into the query latent space and normalize.
        q_latent = self.q_proj_norm(self.q_proj(x))

        # Project the token into the key-value latent space and normalize.
        kv_latent = self.kv_proj_norm(self.kv_proj(x))

        # ========================
        #     Attention Heads
        # ========================

        # Project into query space.
        q = self.q(q_latent)

        # Separate the heads.
        q = q.reshape(B, N, self.num_heads, self.head_dim)


        # TODO - More efficient key and value preparation using `permute` and
        # `chunk`
        #k, v = self.kv(kv_latent).reshape(B, N, 2, self.num_heads, self.head_dim).permute(2, 0, 3, 1, 4).chunk(2, dim=0)
        #k = k.squeeze(0)
        #v = v.squeeze(0)

        # Project into key and value spaces.
        kv = self.kv(kv_latent)

        # Split keys and values.
        kv = kv.reshape(B, N, 2, self.num_heads*self.head_dim)

        # Break apart heads.
        kv = kv.reshape(B, N, 2, self.num_heads, self.head_dim)

        # Separate into two tensors.
        k, v = kv.unbind(2)

        # q, k, v all have shape
        # (batch_size, seq_len, num_heads*head_dim)

        # SDPA Requires:
        # `(Batch, Heads, Sequence, Head_Dim)` or `(B, H, N, D_h)`.
        #
        # We need to swap the dimensions of the heads and the tokens.
        # TODO: Do this more efficiently with permute:
        # q = q.view(B, N, H, D).permute(0, 2, 1, 3)
        q = q.transpose(1, 2)
        k = k.transpose(1, 2)
        v = v.transpose(1, 2)

        # Original ViT:
        #qkv = self.qkv(x).reshape(B, N, 3, self.num_heads, self.head_dim).permute(2, 0, 3, 1, 4)
        #q, k, v = qkv.unbind(0)
        #q, k = self.q_norm(q), self.k_norm(k)

        # SDPA
        x = F.scaled_dot_product_attention(
            q, k, v,
            attn_mask=attn_mask,
            dropout_p=self.attn_drop.p if self.training else 0.,
        )

        # Naive attention, for reference.
        if False:
            q = q * self.scale
            attn = q @ k.transpose(-2, -1)
            attn = maybe_add_mask(attn, attn_mask)
            attn = attn.softmax(dim=-1)
            attn = self.attn_drop(attn)
            x = attn @ v


        # Transpose to switch the tokens and the heads back to (B, N, H, D_h)
        # Then concatenate the value vectors reshape to (B, N, H*D_h)
        x = x.transpose(1, 2).reshape(B, N, self.num_heads * self.head_dim)

        #x = self.norm(x) # Unused by ViT

        # Per-head output projection.
        # This collapses the output down to a single vector (per-token,
        # per-head), which makes the shared output projection cheap to compute.
        x = self.o(x)

        #x = self.o_drop(x) # Unused by ViT

        # Shared output projection.
        if self.output_subspace:
            # RMSNorm on per-head projection hurt performance. I haven't tried
            # putting it on the outside yet.
            #x = self.o_proj(self.o_proj_norm(x))

            # input is (Batch size, Num patches, intermediate dim)
            # output is (Batch size, Num patches, model size)
            x = self.o_proj(x)

        return x

"""**Sanity Check**"""

# 1. Forward‑shape test

# Parameters can be anything.
# This is batch size of 2, 65 patches, model dim of 384
x = torch.randn(2, 65, 384)

# Instantiate.
# model dim 384, 6 heads, projection dims of 256, 192, 192
attn = LatentAttention(
    384,
    6,
    q_proj_dim=256,
    kv_proj_dim=192,
    o_proj_dim=192,
    output_subspace=True
)

# Evaluate.
y = attn(x)

# The output shape should match the input shape.
assert y.shape == x.shape

# 2. Gradient test
y.mean().backward()

# For each parameter,
for p in attn.parameters():

    # Ensure it received a gradient.
    assert p.grad is not None

"""## MLPDecomp

A modified version of the MLP from ViT.

It implements a simple decomposition of the input and output weight matrices. This creates the same concept of shared subspaces.

* On the input side:
  * The token down projection `w1a` is shared across all of the neurons, and receives gradient updates regardless of which neurons fire.
  * The (reduced-size) neuron input weights are in `w1b`.
* The same is true of the output side, in reverse.
"""

class MlpDecomp(nn.Module):
    """ MLP as used in Vision Transformer, MLP-Mixer and related networks

    NOTE: When use_conv=True, expects 2D NCHW tensors, otherwise N*C expected.
    """
    def __init__(
            self,
            in_features,
            latent_dim,
            hidden_features,
            out_features,
            act_layer=nn.GELU,
            norm_layer=None,
            bias=True,
            drop=0.,
            use_conv=False,
    ):
        super().__init__()

        #bias = to_2tuple(bias)
        #drop_probs = to_2tuple(drop)

        # Full MLP:
        #   - 192-dim token
        #   - 768 neurons
        #      - W1 is (192, 768) = (in_features, hidden_features)
        #      - W2 is (768, 192) = (hidden_features, out_features)
        #
        # Decomposed (example)
        #    - W1A is 192 x 64 <-- Bottlenecks the input to latent_dim
        #    - W1B is 64 x 768
        #
        #    - W2A is 768 x 64
        #    - W2B is 64 x 768


        self.w1a = nn.Linear(in_features, latent_dim, bias=False)
        self.w1b = nn.Linear(latent_dim, hidden_features, bias=bias)

        self.act = act_layer()

        #self.drop1 = nn.Dropout(drop_probs[0])
        #self.norm = norm_layer(hidden_features) if norm_layer is not None else nn.Identity()

        self.w2a = nn.Linear(hidden_features, latent_dim, bias=False)
        self.w2b = nn.Linear(latent_dim, out_features, bias=bias)

        #self.drop2 = nn.Dropout(drop_probs[1])

    def forward(self, x):

        x = self.w1a(x) # Shared down projection.
        x = self.w1b(x) #

        x = self.act(x)

        #x = self.drop1(x)
        #x = self.norm(x)

        x = self.w2a(x)
        x = self.w2b(x)

        #x = self.drop2(x)

        return x

"""# ▂▂▂▂▂▂▂▂▂▂▂▂

# Configuration

### 📝 Run Notes
"""

run_notes = """
Adding bias terms to the query, key, and value projections.
"""

"""**Imports**"""

import torch
import torch.nn as nn
import torch.optim as optim
import torchvision
import torchvision.transforms as transforms
from torch.utils.data import DataLoader
from torch.optim.lr_scheduler import CosineAnnealingLR
import timm
from tqdm import tqdm

print(f"PyTorch version: {torch.__version__}")
print(f"timm version: {timm.__version__}")

# Set device
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Using device: {device}")

"""**wandb login**"""

# Install and import wandb
try:
    import wandb
except ImportError:
    print("wandb not found. Installing...")
    !pip install wandb -q
    import wandb

from google.colab import userdata
wandb_key = userdata.get('wandb_api_key')

# Authenticate with wandb
wandb.login(key=wandb_key)

"""**Helper Function for Formatting Counts**"""

def format_size(num):
    """
    This function iterates through a list of suffixes ('K', 'M', 'B') and
    divides the input number by 1024 until the absolute value of the number is
    less than 1024. Then, it formats the number with the appropriate suffix and
    returns the result. If the number is larger than "B", it uses 'T'.
    """
    suffixes = [' ', 'K', 'M', 'B'] # Return an empty space if it's less than 1K,
                                    # this helps highlight the larger values.

    base = 1024

    for suffix in suffixes:
        if abs(num) < base:
            if num % 1 != 0:
                return f"{num:.2f}{suffix}"

            else:
                return f"{num:.0f}{suffix}"

        num /= base

    # Use "T" for anything larger.
    if num % 1 != 0:
        return f"{num:.2f}T"

    else:
        return f"{num:.0f}T"

"""## Model"""

config = {}

config["model_name"] = "vit_tiny_patch16_224"
#config["model_name"] = "vit_small_patch16_224"

print("Creating Vision Transformer model...")

# We create the base model (with pre-trained = False), and then we'll overwrite
# components to test changes.
# There are some quirks here--we have to pass parameters that the base model
# views as valid (i.e., num_heads, embed_dim, and head_dim must align), but then
# we can overwrite them below when we replace the components.
model = timm.create_model(
    config['model_name'],
    pretrained=False,
    num_classes=10,
    patch_size=4,               # 4 × 4 → 8 × 8 = 64 patches (+ [CLS])
    img_size=32,                # CIFAR‑10 native resolution
    num_heads = 4, # Must set this to be divisible here, but can change it below.
                   # Default 3 for tiny, 6 for small
    # xx head_dim = 64, # Can't set this here...
    embed_dim = 256,
    #depth = 12, # Default 12
    mlp_ratio = 4 # Default is 4   320*2.8 = 896
).to(device)

# Record the embedding size and depth, the only two settings we can't overwrite
# further down.
config["embed_dim"] = model.embed_dim
config["depth"] = len(model.blocks)

"""## Swap Components

### Attention
"""

# Choose variant
config["use_mla"] = True

# ====================================
#      Multihead Latent Attention
# ====================================
if config["use_mla"]:

    config["num_heads"] = 12
    config["head_dim"] = 32
    config["output_subspace"] = True # Whether to add the shared output projection.

    config["num_dense_mha"] = 2

    # ======================
    #    Shared Subspaces
    # ======================

    config["q_proj_dim"] = 96
    config["kv_proj_dim"] = 64

    if config["output_subspace"]:
        config["o_proj_dim"] = 96
    else:
        config["o_proj_dim"] = -1

    # For each block,
    for layer_i, blk in enumerate(model.blocks):

        # Leave some dense MHA layers
        if layer_i < config["num_dense_mha"]:
            continue

        # Overwrite with LatentAttention
        blk.attn = LatentAttention(

            dim       = config["embed_dim"],
            num_heads = config["num_heads"],
            head_dim  = config["head_dim"],

            q_proj_dim = config["q_proj_dim"], # 128 has been working well on CIFAR-10. 96 worked equally well on CIFAR-100.
            kv_proj_dim = config["kv_proj_dim"], #
            o_proj_dim = config["o_proj_dim"], # 128 has been working well

            output_subspace = config["output_subspace"]
        )

    # Writing again just to be sure.
    config["num_heads"] = model.blocks[0].attn.num_heads
    config["head_dim"] = model.blocks[0].attn.head_dim

# ============================
#     Standard Attention
# ============================
else:
    # For standard attention, define these up where we created the model.
    config["num_heads"] = model.blocks[0].attn.num_heads
    config["head_dim"] = model.blocks[0].attn.head_dim

    config["q_proj_dim"] = -1
    config["k_proj_dim"] = -1
    config["v_proj_dim"] = -1
    config["kv_proj_dim"] = -1
    config["o_proj_dim"] = -1
    config["output_subspace"] = False

"""### MLPs"""

# Choose Architecture
config["use_decomp_mlp"] = True

# =========================
#    Decomposition MLP
# =========================

# Overwrite with decomposed mlp
if config["use_decomp_mlp"]:

    print("Substituting in Decomposed MLP...")


    config["mlp_num_neurons"] = 1024 # The MLP "hidden size"
    config["num_dense_mlps"] = 2    # Dense MLPs will be sized accoring to model.create
    config["dense_mlp_size"] = model.blocks[0].mlp.fc1.weight.shape[0]
    config["mlp_latent_dim"] = 96  # Intermediate dimension of the decomposition.

    # For each transformer layer,
    for layer_i, blk in enumerate(model.blocks):

        # Leave, e.g., the first two layers dense.
        if layer_i < config["num_dense_mlps"]:
            print(f"Layer {layer_i} is dense with {model.blocks[0].mlp.fc1.weight.shape[0]} neurons.")
            continue

        # Construct the new mlp and overwrite the existing one.
        blk.mlp = MlpDecomp(
            in_features = config["embed_dim"],
            latent_dim = config["mlp_latent_dim"],
            hidden_features = config["mlp_num_neurons"],
            out_features = config["embed_dim"]
        )

# =========================
#    Standard MLP
# =========================

else:
    # Set this above where we created the model.
    config["mlp_num_neurons"] = model.blocks[0].mlp.fc1.weight.shape[0]
    config["num_dense_mlps"] = -1
    config["mlp_latent_dim"] = -1

"""Move the completed model to the GPU"""

# Move to GPU
_ = model.to(device)

"""# Review

### Parameter Tally
"""

## Get all of the model's parameters as a list of tuples.
params = list(model.named_parameters())

print('The model has {:} different named parameters.\n'.format(len(params)))

# =====================
#     Total Params
# =====================

total_params = 0
for p_name, p in params:
    total_params += p.numel()

config["total_elements"] = format_size(total_params)

print(f"Total elements: {config['total_elements']}\n")

# Print out final config
for k, v in config.items():
    print(f"{k:>15}: {v:>10}")

"""## Wandb Run Name"""

if config["use_mla"]:
   dense_str = str(config["num_dense_mha"]) + "mha + "

   # If no output subspace is used, the dimension will show as -1.
   attn_str = dense_str + "mla." + str(config["q_proj_dim"]) + "." + str(config["kv_proj_dim"]) + "." + str(config["o_proj_dim"])


else:
    attn_str = "mha"

# MLP String
if config["use_decomp_mlp"]:
    dense_str = str(config["num_dense_mlps"]) + "mlp." + str(config["dense_mlp_size"]) + " + "

    mlp_str = dense_str + "dcmp." + str(config["mlp_num_neurons"]) + "." + str(config["mlp_latent_dim"])

else:
    mlp_str = "mlp." + str(config["mlp_num_neurons"])

# Example:
# 8.00M - dcmp 800.128.96 - mla 96.64.96 - d384 - ah6.64

run_name = f"{config['total_elements']} - {mlp_str} - {attn_str} - l{config['depth']}.d{config['embed_dim']} - ah{config['num_heads']}.{config['head_dim']}"

print(run_name)

"""## Full Parameter List"""

display_bias = True # Excludes any 1-D parameters.


print("Parameter Name                                              Dimensions       Total Values    Trainable\n")

for p_name, p in params:

    # Loop through the parameter dimensions and delete any == 1.
    p_size = list(p.size())

    for i in range(len(p_size) - 1, -1, -1):
        if p_size[i] == 1:
            del p_size[i]

    if len(p_size) == 1:
        if not display_bias:
            continue
        p_dims = "{:>10,} x {:<10}".format(p.size()[0], "-")

    elif len(p_size) == 2:
        p_dims = "{:>10,} x {:<10,}".format(p.size()[0], p.size()[1])
    elif len(p_size) == 3:
        p_dims = "{:>10,} x {:,} x {:<10}".format(p.size()[0], p.size()[1], p.size()[2])
    elif len(p_size) == 4:
        p_dims = "{:>10,} x {:,} x {:,} x {:<10}".format(p.size()[0], p.size()[1], p.size()[2], p.size()[3])
    else:
        print("Unexpected: ", p.size(), p_name)
        break

    print("{:<55} {:}    {:>6}    {:}".format(p_name, p_dims, format_size(p.numel()), p.requires_grad))


print(f"\nTotal elements: {format_size(total_params)}\n")

"""# ▂▂▂▂▂▂▂▂▂▂▂▂

# Training
"""

# Hyperparameters

config = {
    "epochs": 100, # Increased epochs for better convergence
    "lr": 5e-4, # 0.001 = 1e-3   0.0005 = 5e-4
    "optimizer": "adamw",
    "weight_decay": 0.05,
    "scheduler": "cosine",
    "warmup_epochs": 5,
    "batch_size": 512,
}

"""### Data Prep

GPT suggested a number of improvements to the transforms section, but I've left them out to keep results consistent.
"""

print("\nPreparing CIFAR-10 dataset with augmentations...")

from timm.data import Mixup

# Suggested improvement:
#CIFAR10_MEAN = (0.4914, 0.4822, 0.4465)
#CIFAR10_STD  = (0.2023, 0.1994, 0.2010)


# Add transformations to give the model additional training data.
train_transform = transforms.Compose([
    # Suggested improvement:
    #transforms.RandAugment(num_ops=2, magnitude=9),  # RandAug (2, 9)
    transforms.RandomCrop(32, padding=4),
    transforms.RandomHorizontalFlip(),
    transforms.ToTensor(),
    transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5))
    #transforms.Normalize(CIFAR10_MEAN, CIFAR10_STD),
])


# No transformations on test set.
test_transform = transforms.Compose([
    transforms.ToTensor(),
    transforms.Normalize((0.5, 0.5, 0.5), (0.5, 0.5, 0.5))
    #transforms.Normalize(CIFAR10_MEAN, CIFAR10_STD),
])

"""
Another suggested improvement:
mixup_fn = Mixup(                           # timm >= 0.9
    mixup_alpha=0.2,
    cutmix_alpha=1.0,      # ≈ CutMix prob 0.1 when switch_prob=0.5
    prob=1.0,
    switch_prob=0.5,
    label_smoothing=0.1,
    num_classes=10,
)
"""

# Load datasets with new transforms

# CIFAR-10
train_dataset = torchvision.datasets.CIFAR10(root='./data', train=True, download=True, transform=train_transform)
test_dataset = torchvision.datasets.CIFAR10(root='./data', train=False, download=True, transform=test_transform)

# CIFAR-100
#train_dataset = torchvision.datasets.CIFAR100(root='./data', train=True, download=True, transform=train_transform)
#test_dataset = torchvision.datasets.CIFAR100(root='./data', train=False, download=True, transform=test_transform)

train_loader = DataLoader(
    train_dataset,
    batch_size=config['batch_size'],
    shuffle=True,
    num_workers=4, # Loading is a little heavy due to transforms.
    pin_memory=True
)
test_loader = DataLoader(
    test_dataset,
    batch_size=config['batch_size'],
    shuffle=False,
    num_workers=4,
    pin_memory=True
)

"""### Functions"""

wandb.init(
    project = "vit-mla-cifar10",
    #project = "vit-cifar100-testbed",
    config = config,
    name = run_name,
    notes = run_notes
)

from timm.loss import SoftTargetCrossEntropy

criterion = nn.CrossEntropyLoss()
#criterion = SoftTargetCrossEntropy()        # works for hard‑ or soft‑labels


optimizer = optim.AdamW(
    model.parameters(),
    lr=config['lr'],
    weight_decay=config['weight_decay']
)

# Use a cosine annealing scheduler
scheduler = CosineAnnealingLR(
    optimizer,
    T_max = config['epochs'] - config['warmup_epochs']
)

import time
import torch.profiler


def train_one_epoch(model, loader, criterion, optimizer, device, epoch, config):
    model.train()
    running_loss = 0.0
    total_samples = 0

    # Define CUDA events to measure GPU flops only.
    start_event = torch.cuda.Event(enable_timing=True)
    end_event   = torch.cuda.Event(enable_timing=True)

    # Allow previous epoch to finish, then start the cuda timing.
    torch.cuda.synchronize()
    start_event.record()

    progress_bar = tqdm(loader, desc=f"Training Epoch {epoch+1}/{config['epochs']}")

    # Manual warmup logic.
    # If we're still in the warm up period,
    if epoch < config['warmup_epochs']:
        # Fraction of the warmup period
        lr_scale = (epoch + 1) / config['warmup_epochs']

        for g in optimizer.param_groups:
            g['lr'] = config['lr'] * lr_scale

    # For each batch of images...
    for images, labels in progress_bar:

        # Move to the GPU
        images, labels = images.to(device), labels.to(device)

        # Clear gradients
        optimizer.zero_grad()

        # Forward pass
        outputs = model(images)

        # Evaluate loss from predictions.
        loss = criterion(outputs, labels)

        # Backprop
        loss.backward()

        # Update weights.
        optimizer.step()

        # Update tracking values.
        running_loss += loss.item()
        total_samples += images.size(0)

        # TODO - Displays the wrong loss?
        progress_bar.set_postfix(loss=f"{loss.item():.4f}")

    # Stop the CUDA timer.
    end_event.record()
    torch.cuda.synchronize()

    elapsed_ms = start_event.elapsed_time(end_event)   # GPU time only

    samples_per_sec = total_samples / (elapsed_ms / 1_000)

    # After warm-up epochs, step the scheduler
    if epoch >= config['warmup_epochs']:
        scheduler.step()

    current_lr = optimizer.param_groups[0]['lr']

    # Log stats.
    wandb.log({
        "epoch": epoch,
        "learning_rate": current_lr,
        "train_samples_per_sec": samples_per_sec
    })

    return running_loss / len(loader)

def evaluate(model, loader, criterion, device):
    model.eval()
    correct = 0
    total = 0
    running_loss = 0.0
    with torch.no_grad():
        for images, labels in tqdm(loader, desc="Evaluating", leave=False):
            images, labels = images.to(device), labels.to(device)
            outputs = model(images)
            loss = criterion(outputs, labels)
            running_loss += loss.item()
            _, predicted = torch.max(outputs.data, 1)
            total += labels.size(0)
            correct += (predicted == labels).sum().item()
    accuracy = 100 * correct / total
    avg_loss = running_loss / len(loader)
    return avg_loss, accuracy

"""### Loop"""

import time

train_start_time = time.time()
all_test_accuracies = []
total_tokens = 0

try:

    # For pass of the training set,
    for epoch in range(config['epochs']):

        # Train on the dataset.
        train_loss = train_one_epoch(model, train_loader, criterion, optimizer, device, epoch, config)

        # Run evaluation
        test_loss, test_acc = evaluate(model, test_loader, criterion, device)

        all_test_accuracies.append(test_acc)

        # Track total samples seen
        total_tokens += len(train_loader.dataset)

        # Log metrics to wandb
        wandb.log({
            "epoch": epoch,
            "train_loss": train_loss,
            "test_loss": test_loss,
            "test_accuracy": test_acc
        })

        print(f"Epoch {epoch+1}/{config['epochs']} | "
            f"Train Loss: {train_loss:.4f} | "
            f"Test Loss: {test_loss:.4f} | "
            f"Test Accuracy: {test_acc:.2f}%")

# Make sure `wandb.finish()` is called even if there's an exception.
finally:

    # Check in case the run failed with an exception before completing an epoch.
    if len(all_test_accuracies) > 0:

        # Summary statistics for table.
        max_test_acc = max(all_test_accuracies)
        avg_tokens_sec = total_tokens / (time.time() - train_start_time)

        # Create a table with column headers
        summary_table = wandb.Table(columns=[
            "Notes", "Max Test Accuracy", "Avg Tokens/Sec"
        ])

        # Add a row of data
        summary_table.add_data(
            run_notes,
            f"{max_test_acc:.2f}%",
            f"{avg_tokens_sec:.0f}",
        )

        # Log the summary table
        wandb.log({"run_summary": summary_table})

    wandb.finish()



"""# ▂▂▂▂▂▂▂▂▂▂▂▂

# Reference

### Cost-Benefit Tool

GPT put this together for me to calculate what kind of parameter/FLOP savings a particular combination of settings will yield.
"""

def summarize_shared_subsp ace_projection(
    head_dim=128,
    num_heads=32,
    output_dim=4096,
    intermediate_dim=1024,
    num_groups=4
):
    # Group config
    heads_per_group = num_heads // num_groups
    rows_per_group = heads_per_group * head_dim  # stacked row count

    # ========== Parameter Counts ==========
    # Baseline: one full matrix per head
    baseline_params = num_heads * head_dim * output_dim

    # Shared: each group has 1 B, and n A_i
    A_params_per_group = heads_per_group * head_dim * intermediate_dim
    B_params_per_group = intermediate_dim * output_dim
    shared_params = num_groups * (A_params_per_group + B_params_per_group)

    # ========== FLOPs ==========
    # Baseline: each head does x @ W^O (128x4096)
    flops_per_head_baseline = 2 * head_dim * output_dim
    total_flops_baseline = num_heads * flops_per_head_baseline

    # Shared: each head does x @ A_i (128xR), then @ B (R x 4096)
    flops_per_head_shared = (
        2 * head_dim * intermediate_dim +
        2 * (intermediate_dim * output_dim) / heads_per_group
    )
    total_flops_shared = num_heads * flops_per_head_shared

    # ========== Break-even rank ==========
    numerator = heads_per_group * head_dim * output_dim
    denominator = heads_per_group * head_dim + output_dim
    break_even_rank = numerator / denominator

    # ========== Output Formatting ==========
    def fmt(x):
        if abs(x) >= 2**20:
            return f"{x / 2**20:.1f}M"
        elif abs(x) >= 2**10:
            return f"{x / 2**10:.1f}K"
        return str(x)

    print("\n🔢 Parameter Counts:")
    print(f"  Baseline:         {fmt(baseline_params)}")
    print(f"  Shared subspace:  {fmt(shared_params)}")
    print(f"  Change:           {fmt(shared_params - baseline_params)}  (Negative is good)")
    print(f"  Percentage:       {100 * (shared_params - baseline_params) / baseline_params:.1f}%")

    print("\n⚙️  Compute (FLOPs):")
    print(f"  Baseline:         {fmt(total_flops_baseline)}")
    print(f"  Shared subspace:  {fmt(int(total_flops_shared))}")
    print(f"  Change:           {fmt(int(total_flops_shared - total_flops_baseline))} (Negative is good)")
    print(f"  Percentage:       {100 * (total_flops_shared - total_flops_baseline) / total_flops_baseline:.1f}%")

    print("\n📐 Subspace Geometry:")
    print(f"  Rows per group:   {rows_per_group}")
    print(f"  Intermediate dim: {intermediate_dim}")
    print(f"  Ratio:            {rows_per_group / intermediate_dim:.2f}  (Higher means we're stuffing more)")
    print(f"\n  ----------------------------\n")
    print(f"  Break-even rank:  {break_even_rank:.1f} → current r = {intermediate_dim}")

# Example usage
summarize_shared_subspace_projection(
    head_dim=64,
    num_heads=6,
    output_dim=384,
    intermediate_dim=128,
    num_groups=1
)
